version: '3.8'
services:
  poolcontroller:
    image: gemini9674/nodejs-poolcontroller
    container_name: nodejs-poolcontroller
    volumes:
    - nodejs-poolcontroller-data:/app/config # Mount your config.json directory
    - nodejs-poolcontroller-data:/app/data # Optional: for persistent data
    restart: unless-stopped
volumes:
  nodejs-poolcontroller-data:
